import { Inter } from "next/font/google";
import { Theme, ThemePanel } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
// import '@radix-ui/themes/tokens.css';
// import '@radix-ui/themes/components.css';
// import '@radix-ui/themes/utilities.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
        <Theme 
        appearance="dark"
        radius="medium"
        panelBackground="solid"
        >
          {children}
          </Theme>
        </body>
    </html>
  );
}

